### ISSUE TITLE
세션 로그인 여부 표시 버그

### ISSUE THREAD

**Issue by bluepeng9** [spring-problem/spring-login#24]
**버그 설명**

세션 로그인 이전임에도 로그인 되었다고 나타나는 현상

**재현 방법**

1. 세션 로그인 설정
2. 홈페이지 접속
3. 로그인 여부 확인 시 true

**예상 동작**

로그인 이전이므로 빈 값이 출력되어야 함

**Comment by junyoung-choe** [comment]
홈페이지로 매핑해주는 부분에서 해당 세션이 가지고 있는 토큰값으로 꺼내온 ID 가 있을때만 로그인 여부가 확인되도록 변경했습니다.
